services:
  - type: web
    name: hrms-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port $PORT main:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./hrms.db
      - key: PYTHONUNBUFFERED
        value: true